[package]
name = "puimuri-trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.9"

[dev-dependencies]
approx = "0.5.1"
