name: Build and Deploy to GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Get Git commit SHA
      id: commit
      run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.SERVICE_NAME }}:${{ steps.commit.outputs.sha }} .

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

    - name: Push Docker image to Artifact Registry
      run: docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.SERVICE_NAME }}:${{ steps.commit.outputs.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Get Git commit SHA
      id: commit
      run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    # - name: Deploy to Cloud Run
    #   run: |
    #     gcloud run deploy ${{ vars.SERVICE_NAME }} \
    #       --image ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.SERVICE_NAME }}:${{ steps.commit.outputs.sha }} \
    #       --region ${{ vars.REGION }} \
    #       --allow-unauthenticated \
    #       --project ${{ vars.PROJECT_ID }} \
    #       --service-account ${{ vars.SERVICE_NAME }}@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com
